<a href="https://colab.research.google.com/github/chetools/CHE3026_Spring2026/blob/main/DimensionalAnalysisNullSpace.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import scipy as sp

In [10]:
A = np.array([[0, 0, 0, 1, 1, 1],
              [1, 1, 1, -3, -1, -1],
              [0, 0, -1, 0, -1, -2.]])

In [11]:
ns=sp.linalg.null_space(A)
ns

array([[-0.43021839, -0.59890126, -0.28500775],
       [ 0.66546381, -0.05339808,  0.42344606],
       [ 0.43898326,  0.01222794, -0.68833919],
       [ 0.33711434, -0.3200357 , -0.27495044],
       [-0.23524541,  0.65229934, -0.13843832],
       [-0.10186892, -0.33226364,  0.41338875]])

In [12]:
n1,n2,n3=ns[:,0], ns[:,1], ns[:,2]

In [13]:
z = 20.*n1 + 50*n2 + 2*n3
z

array([-39.11944638,  11.48626438,   8.01438392,  -9.80939904,
        27.633182  , -17.82378296])

In [14]:
A@z

array([-1.06581410e-14, -1.42108547e-14, -3.55271368e-15])

In [15]:
##ns[(0,4,5),:] @ c1 = np.array([1, 0, 0.])

In [16]:
c1 = np.linalg.solve(ns[(0,4,5),:], np.array([1, 0, 0.]))
c1

array([-1.0956822 , -0.54550318, -0.70845381])

In [17]:
ns @ c1  #pi1 = L/D

array([ 1.00000000e+00, -1.00000000e+00,  1.15969912e-16,  5.87769572e-16,
       -1.32023599e-16,  2.07514929e-17])

In [18]:
c2 = np.linalg.solve(ns[(0,4,5),:], np.array([0, 1, 0.]))
c2

array([-1.67680682,  1.01350517,  0.40140525])

In [19]:
ns @ c2 # mu/(rho V D)

array([ 6.31259147e-17, -1.00000000e+00, -1.00000000e+00, -1.00000000e+00,
        1.00000000e+00,  3.75839170e-17])

In [20]:
c3 = np.linalg.solve(ns[(0,4,5),:], np.array([0, 0, 1.]))
c3

array([-1.31694978, -0.03668383,  2.06501758])

In [21]:
ns@c3 # deltaP/(rho*v**2)

array([-5.36761267e-17,  5.37529203e-16, -2.00000000e+00, -1.00000000e+00,
       -5.42006681e-17,  1.00000000e+00])