<a href="https://colab.research.google.com/github/chetools/CHE3026_Spring2026/blob/main/PipeDataAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import pandas as pd
df = pd.read_excel("PipeFlowData.xlsx", sheet_name='Sheet1')

In [ ]:
df

dP         V       L     D     rho        mu
0    1.329313  0.018407  100.00  0.10  1000.0  0.001000
1    1.331944  0.014730  100.00  0.10  1000.0  0.001000
2    1.002106  0.012323  100.00  0.10  1000.0  0.001000
3    0.634434  0.017720   50.00  0.10  1000.0  0.001000
4    0.781574  0.018174   50.00  0.10  1000.0  0.001000
..        ...       ...     ...   ...     ...       ...
423  0.058715  0.838762    0.05  0.01     1.2  0.000018
424  0.039887  0.513199    0.05  0.01     1.2  0.000018
425  0.001123  0.015573    0.05  0.01     1.2  0.000018
426  0.005102  0.070848    0.05  0.01     1.2  0.000018
427  0.023750  0.329263    0.05  0.01     1.2  0.000018

[428 rows x 6 columns]

In [3]:
LD = (df['L']/df['D']).values
Re = (df['rho']*df['V']*df['D']/df['mu']).values
dPrhov2 = (df['dP']/df['rho']/df['V']**2).values

In [4]:
import plotly.express as px

fig = px.scatter_3d(x=LD, y=Re, z=dPrhov2, labels={'x': 'LD', 'y': 'Re', 'z': 'dPrhov2'})
fig.update_layout(title='3D Scatter Plot of LD, Re, and dPrhov2', scene_xaxis_type='log', scene_yaxis_type='log', scene_zaxis_type='log')
fig.show()

In [13]:
A = np.c_[np.ones_like(Re), np.log(Re), np.log(LD)]

In [14]:
A

array([[1.        , 7.51787628, 6.90775528],
       [1.        , 7.29508411, 6.90775528],
       [1.        , 7.11662735, 6.90775528],
       ...,
       [1.        , 2.34008768, 1.60943791],
       [1.        , 3.85506546, 1.60943791],
       [1.        , 5.39139274, 1.60943791]])

In [15]:
A.T @ A

array([[  428.        ,  2479.88718489,  1870.25531144],
       [ 2479.88718489, 15182.79492284, 10859.05432399],
       [ 1870.25531144, 10859.05432399,  9495.10760351]])

In [16]:
A.T @ np.log(dPrhov2)

array([ 280.18538388,  830.45256958, 2523.967239  ])

In [18]:
np.linalg.solve(A.T @ A, A.T @ np.log(dPrhov2))

array([ 2.09089443, -1.00186381,  0.99975217])